#!/bin/bash

## Note
# Backing up to an exFAT drive will lose your permissions info
# as exFAT does not support permissions.

## Config
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
BACKUP_LIST="$scriptDir/backup-list.txt"
BACKUP_DIR='/Volumes/Backup Plus/BACKUPS'
BACKUP_LOG_FILE='backup.log'

origList=$(cat $BACKUP_LIST | grep -v -E '(^#|^\s*$)')  # Exclude empty lines and #s
list=${origList//\~/$HOME}                              # Replace '~' with '$HOME'

## Validate the backup locations
invalid=false
for item in $list; do
    if [[ ! -f $item && ! -d $item ]]; then
        echo "$item is invalid."
        invalid=true
    fi
done
if $invalid; then
    exit 1
fi

## Prompt for confirmation
echo "These locations will be backed up to $BACKUP_DIR:"
for item in $origList; do
    echo $item
done
read -p 'Do you wish to proceed? (y) ' y
if [[ $y != 'y' ]]; then
    exit 0
fi

## Backup using rsync
rsync --archive \
      --delete \
      --progress \
      --human-readable \
      --exclude="node_modules" \
      --exclude=".DS_Store" \
      $list \
      "$BACKUP_DIR" \
      | tee "$BACKUP_DIR/$BACKUP_LOG_FILE"

