#!/bin/bash

date=$(TZ=Singapore date +%Y-%m-%d)
BACKUP_DIR='/Volumes/Backup Plus/BACKUPS/'
BACKUP_DUMP="backup-$date.tar.gz"

# Prompt
echo "Ensure that there is sufficient disk space in the current directory $(pwd)."
read -p "This will zip $BACKUP_DIR into $BACKUP_DUMP. Continue? (y) " y
if [[ $y != 'y' ]]; then
    echo 'Exiting.'
    exit 0
fi

# Calculate size
echo 'Calculating size...'
size=$(du -sk "$BACKUP_DIR" | cut -f 1)
echo "Size is $size kiB"

# Backup with progress bar
tar cf - "$BACKUP_DIR" | pv -s ${size}k | gzip > "$BACKUP_DIR$BACKUP_DUMP"

